### PR TITLE
Add the formbuilder and components gems to the boilerplate

### PR DESCRIPTION
**Pull request by peteryates**
### Context

Just about every application generated from this boilerplate will need to implement the form behaviours and component designs specified in the [GOV.UK Design System](https://design-system.service.gov.uk/). Using a bespoke form implementation per application results in many incomplete implementations and lots of duplicated work. This is an attempt to alleviate that effort.

### Changes proposed in this pull request

Add the [form builder](https://github.com/dfe-digital/govuk_design_system_formbuilder/) and [components](https://github.com/dfe-digital/govuk-components) gems to the standard boilerplate and add a skeleton config for the formbuilder.

Both libraries are already widely used with the components gem already used across several DfE services and the form builder used by approximately [~~20~~ 45 services across multiple government departments](https://github.com/DFE-Digital/govuk_design_system_formbuilder/network/dependents?package_id=UGFja2FnZS00NDY2MTY4OTg%3D).

The main layout (`app/views/layouts/application.html.erb`) has been updates to use the header and footer components, the output is identical with a [huge reduction in markup](https://github.com/DFE-Digital/govuk-rails-boilerplate/commit/e636857c534d126467ccab4ce0b8ebc3b8ca7702).

| Before | After |
| ------ | ------ |
| Screenshot from 2020-12-30 11-21-10 | Screenshot from 2020-12-30 11-22-52 |

### Guidance to review

It's worth having a discussion before this is merged.

My feeling is that it'll remove lots of legwork in the long run and make upgrading to newer versions of the design system more straightforward and easier to test.

The potential risk is that people don't want them or find them useful and then there's an additional task of removing them after the boilerplate is used.

### CODE REVIEW

**Review by dankmitchell — APPROVED** [review]
I’m onboard with this @peteryates !

Nice work! LGTM

**Review by benilovj — APPROVED** [review]
Yep these are good defaults to start with. 👍

**Comment by peteryates** [comment]
My force push was so I could rebase `master` to avoid the `Gemfile.lock` conflict btw ☝🏽

**Review by dankmitchell — APPROVED** [review]

**Review by defong — APPROVED** [review]

**Comment by paulrobertlloyd** [comment]
Pointed to this PR by @dankmitchell. I love it! What’s preventing this from getting merged?

**Comment by paulrobertlloyd** [comment]
Merge, merge, merge!

**Pull request merged**
